package:
  name: msnpy
  version: 0.1.7


source:
  git_url: https://github.com/computational-metabolomics/msnpy.git


build:
  skip: True # [py3k]
  number: 0
  entry_points:
    - msnpy = msnpy.__main__:main 


requirements:
  host:
    - 'python 2.7.*'
    - dimspy
    - pymzml <=2.0.0
    - pandas
    - networkx
    - mysql-connector-python
  run:
    - 'python 2.7.*'
    - dimspy
    - pymzml <=2.0.0
    - pandas
    - networkx
    - mysql-connector-python

test:
  imports:
    - msnpy

  commands:
    - msnpy --help


about:
  home: http://www.github.com/computational-metabolomics/msnpy
  license: GNU General Public License v3.0
  summary: 'Python Package to process and annotate multi-stage mass spectrometry data'
  license_family: GPL3
